server:
  port: 8090
spring:
  application:
    name: madfs
  # ?? multipart ????
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
madfs:
  path: ${user.home}/madfs
  downloadUrl: http://localhost:8090/download   # ???????
  autoMd5: true                                  # ???? MD5
  group: C8090                    # ???????????
rocketmq:
  name-server: localhost:9876     # RocketMQ NameServer ??
  producer:
    group: madfs-producer         # ??????????????

